[build]
  publish = "."
  command = "node generate-styles.js"

[build.environment]
  NODE_VERSION = "18"

# Configuration pour Netlify CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200