backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "config"
    label: "Configuration du site"
    files:
      - label: "Informations générales"
        name: "general"
        file: "data/general.yml"
        fields:
          - { label: "Nom du cabinet", name: "site_name", widget: "string" }
          - { label: "Titre de la page", name: "site_title", widget: "string" }
          - { label: "Description", name: "site_description", widget: "text" }
          - { label: "Téléphone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Adresse", name: "address", widget: "text" }
          - { label: "Horaires", name: "hours", widget: "string" }

  - name: "colors"
    label: "Couleurs du site"
    files:
      - label: "Palette de couleurs"
        name: "colors"
        file: "data/colors.yml"
        fields:
          - { label: "Couleur principale", name: "primary_color", widget: "color" }
          - { label: "Couleur principale au survol", name: "primary_hover", widget: "color" }
          - { label: "Couleur principale foncée", name: "primary_dark", widget: "color" }
          - { label: "Couleur d'accent", name: "accent_color", widget: "color" }
          - { label: "Couleur du texte", name: "text_color", widget: "color" }
          - { label: "Couleur de fond", name: "background_color", widget: "color" }

  - name: "fonts"
    label: "Polices du site"
    files:
      - label: "Configuration des polices"
        name: "fonts"
        file: "data/fonts.yml"
        fields:
          - label: "Police des titres"
            name: "heading_font"
            widget: "select"
            options:
              - { label: "Inter", value: "Inter" }
              - { label: "Roboto", value: "Roboto" }
              - { label: "Open Sans", value: "Open Sans" }
              - { label: "Lato", value: "Lato" }
              - { label: "Montserrat", value: "Montserrat" }
              - { label: "Poppins", value: "Poppins" }
              - { label: "Nunito", value: "Nunito" }
              - { label: "Playfair Display", value: "Playfair Display" }
              - { label: "Merriweather", value: "Merriweather" }
              - { label: "Crimson Text", value: "Crimson Text" }
              - { label: "Libre Baskerville", value: "Libre Baskerville" }
              - { label: "Source Serif Pro", value: "Source Serif Pro" }
          - label: "Police du texte"
            name: "body_font"
            widget: "select"
            options:
              - { label: "Inter", value: "Inter" }
              - { label: "Roboto", value: "Roboto" }
              - { label: "Open Sans", value: "Open Sans" }
              - { label: "Lato", value: "Lato" }
              - { label: "Source Sans Pro", value: "Source Sans Pro" }
              - { label: "Nunito", value: "Nunito" }
              - { label: "Work Sans", value: "Work Sans" }
              - { label: "Fira Sans", value: "Fira Sans" }
          - label: "Police d'accent"
            name: "accent_font"
            widget: "select"
            options:
              - { label: "Playfair Display", value: "Playfair Display" }
              - { label: "Merriweather", value: "Merriweather" }
              - { label: "Crimson Text", value: "Crimson Text" }
              - { label: "Libre Baskerville", value: "Libre Baskerville" }
              - { label: "Source Serif Pro", value: "Source Serif Pro" }
              - { label: "Cormorant Garamond", value: "Cormorant Garamond" }
              - { label: "Lora", value: "Lora" }
              - { label: "Bitter", value: "Bitter" }
          - label: "Poids des titres"
            name: "heading_weights"
            widget: "select"
            options:
              - { label: "Léger (300,400)", value: "300,400" }
              - { label: "Normal (400,500,600)", value: "400,500,600" }
              - { label: "Gras (400,600,700)", value: "400,600,700" }
              - { label: "Très gras (500,700,900)", value: "500,700,900" }
          - label: "Poids du texte"
            name: "body_weights"
            widget: "select"
            options:
              - { label: "Léger (300,400)", value: "300,400" }
              - { label: "Normal (400,500)", value: "400,500" }
              - { label: "Moyen (400,500,600)", value: "400,500,600" }

  - name: "hero"
    label: "Section Hero"
    files:
      - label: "Hero"
        name: "hero"
        file: "data/hero.yml"
        fields:
          - { label: "Titre principal", name: "title", widget: "string" }
          - { label: "Mot en surbrillance", name: "highlight", widget: "string" }
          - { label: "Sous-titre", name: "subtitle", widget: "text" }
          - { label: "Bouton principal", name: "primary_button", widget: "string" }
          - { label: "Bouton secondaire", name: "secondary_button", widget: "string" }
          - { label: "Image hero", name: "hero_image", widget: "image", required: false }

  - name: "expertise"
    label: "Domaines d'expertise"
    files:
      - label: "Expertise"
        name: "expertise"
        file: "data/expertise.yml"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Sous-titre", name: "subtitle", widget: "text" }
          - label: "Domaines"
            name: "domains"
            widget: "list"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Icône SVG", name: "icon", widget: "text" }

  - name: "cabinet"
    label: "Section Cabinet"
    files:
      - label: "Cabinet"
        name: "cabinet"
        file: "data/cabinet.yml"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Sous-titre", name: "subtitle", widget: "text" }
          - label: "Membres de l'équipe"
            name: "team"
            widget: "list"
            fields:
              - { label: "Nom", name: "name", widget: "string" }
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Citation", name: "quote", widget: "text", required: false }
              - { label: "Photo", name: "photo", widget: "image", required: false }

  - name: "actualites"
    label: "Actualités"
    folder: "data/actualites"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Extrait", name: "excerpt", widget: "text" }
      - { label: "Catégorie", name: "category", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Page Contact"
        name: "contact"
        file: "data/contact.yml"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Sous-titre", name: "subtitle", widget: "text" }
          - { label: "Titre section info", name: "info_title", widget: "string" }